### ISSUE TITLE
Flaky test `NodeArrayFutureTest.testTimeoutIsSpread()`

### ISSUE THREAD

**Issue by lorban** [jetty-project/jetty-cluster-orchestrator#192]
The following failure sometimes happen with JDK 17:

```
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 79.05 s <<< FAILURE! -- in org.mortbay.jetty.orchestrator.NodeArrayFutureTest
[ERROR] org.mortbay.jetty.orchestrator.NodeArrayFutureTest.testTimeoutIsSpread -- Time elapsed: 14.65 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Expected java.util.concurrent.TimeoutException to be thrown, but nothing was thrown.
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:73)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3115)
	at org.mortbay.jetty.orchestrator.NodeArrayFutureTest.testTimeoutIsSpread(NodeArrayFutureTest.java:135)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by lorban** [comment]
This problem is actually in the test itself, the rest of the code is just fine.
