### ISSUE TITLE
UnsupportedOperationException when trying to copy files from a NodeArray's root path

### ISSUE THREAD

**Issue by lorban** [jetty-project/jetty-cluster-orchestrator#209]
When using Jetty 12's `org.eclipse.jetty.util.IO.copyDir()` helper to copy a `NodeArray`'s root path, the following exception is thrown:

```
java.lang.UnsupportedOperationException
	at org.mortbay.jetty.orchestrator.nodefs.NodeFileSystemProvider.getFileAttributeView(NodeFileSystemProvider.java:89)
	at java.base/java.nio.file.Files.getFileAttributeView(Files.java:1790)
	at java.base/java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:110)
	at java.base/java.nio.file.Files.copy(Files.java:1307)
...
```

**Comment by joakime** [comment]
Try use the IO.copyDir() version that takes two Path objects, not File objects.

https://github.com/jetty/jetty.project/blob/jetty-12.0.8/jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IO.java#L243

**Comment by lorban** [comment]
@joakime that's exactly the version that was used, so I modified the description to reflect that.

The problem seems to be that JDK 21 takes a different codepath through the orchestrator's `NodeFileSystemProvider` than JDK 17 used to take. And that new codepath seems to call a method that hasn't been implemented yet: `NodeFileSystemProvider.getFileAttributeView()` unconditionally throws `UnsupportedOperationException`.

I'm going to check what it takes to replace SSHJ with Apache Mina SSH, as they already have a sftp nio Filesystem implementation we could simply wrap. An extra benefit would be that the orchestrator's node filesystem would support writing to it, which would allow uploading files to the nodes.

If that is too much work, I'll try to come up with an implementation of `NodeFileSystemProvider.getFileAttributeView()` with SSHJ.

**Comment by lorban** [comment]
Implemented on top of SSHJ.
